config/routes.rb
Rails.application.routes.draw do
  resources :tickets
  resources :events
  #get 'ticketing/index'

  root 'ticketing#index'
  get 'ticketing/tickets'
  get 'ticketing/payment'
  get 'ticketing/code'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/event.rb
class Event < ApplicationRecord
end

app/models/ticket.rb
class Ticket < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, only: %i[ show edit update destroy ]

  # GET /events or /events.json
  def index
    @events = Event.all
    @name = params[:name]
    @email = params[:email]


  end

  # GET /events/1 or /events/1.json
  def show
  end

  # GET /events/new
  def new
    @event = Event.new
  end

  # GET /events/1/edit
  def edit
  end

  # POST /events or /events.json
  def create
    @event = Event.new(event_params)

    respond_to do |format|
      if @event.save
        format.html { redirect_to @event, notice: "Event was successfully created." }
        format.json { render :show, status: :created, location: @event }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /events/1 or /events/1.json
  def update
    respond_to do |format|
      if @event.update(event_params)
        format.html { redirect_to @event, notice: "Event was successfully updated." }
        format.json { render :show, status: :ok, location: @event }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1 or /events/1.json
  def destroy
    @event.destroy
    respond_to do |format|
      format.html { redirect_to events_url, notice: "Event was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_event
      @event = Event.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def event_params
      params.require(:event).permit(:name, :date, :location, :seats, :price)
    end
end

app/controllers/ticketing_controller.rb
class TicketingController < ApplicationController
  def index
    @name = params[:name]
    @email = params[:email]
  end

  def code
    @name = params[:name]
    @code = SecureRandom.uuid

    while Ticket.find_by_code(@code) != nil
      @code = SecureRandom.uuid
    end
    @event = Event.find(params[:event])
    @new_seats = @event.seats - 1
    query = "UPDATE events set seats = " + @new_seats.to_s+" WHERE id = " + params[:event]
    ActiveRecord::Base.connection.execute(query)
    object = Ticket.new(:name => params[:name], :email => params[:email], :event => @event.name, :code => @code.to_s)
    object.save

  end

end

app/controllers/tickets_controller.rb
class TicketsController < ApplicationController
  before_action :set_ticket, only: %i[ show edit update destroy ]

  # GET /tickets or /tickets.json
  def index
    @tickets = Ticket.all
  end

  # GET /tickets/1 or /tickets/1.json
  def show
  end

  # GET /tickets/new
  def new
    @ticket = Ticket.new
  end

  # GET /tickets/1/edit
  def edit
  end

  # POST /tickets or /tickets.json
  def create
    @ticket = Ticket.new(ticket_params)

    respond_to do |format|
      if @ticket.save
        format.html { redirect_to @ticket, notice: "Ticket was successfully created." }
        format.json { render :show, status: :created, location: @ticket }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @ticket.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tickets/1 or /tickets/1.json
  def update
    respond_to do |format|
      if @ticket.update(ticket_params)
        format.html { redirect_to @ticket, notice: "Ticket was successfully updated." }
        format.json { render :show, status: :ok, location: @ticket }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @ticket.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tickets/1 or /tickets/1.json
  def destroy
    @ticket.destroy
    respond_to do |format|
      format.html { redirect_to tickets_url, notice: "Ticket was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_ticket
      @ticket = Ticket.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def ticket_params
      params.require(:ticket).permit(:name, :email, :event, :code)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/tickets_helper.rb
module TicketsHelper
end

app/views/events/_form.html.erb
<%= form_with(model: event) do |form| %>
  <% if event.errors.any? %>
    <div id="error_explanation" class="form-group">
      <h2><%= pluralize(event.errors.count, "error") %> prohibited this event from being saved:</h2>

      <ul>
        <% event.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field" >
    <%= form.label :name %>
    <%= form.text_field :name, class: "form-control"%>
  </div>

  <div class="field">
    <%= form.label :date %>
    <%= form.datetime_select :date, class: "form-control"%>
  </div>

  <div class="field">
    <%= form.label :location %>
    <%= form.text_field :location, class: "form-control" %>
  </div>

  <div class="field">
    <%= form.label :seats %>
    <%= form.number_field :seats, class: "form-control" %>
  </div>

  <div class="field">
    <%= form.label :price %>
    <%= form.number_field :price, class: "form-control" %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/events/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Events</h1>

<table class="table">
  <thead class ="thead-dark">
    <tr>
      <th scope="col">Name</th>
      <th scope="col">Date</th>
      <th scope="col">Location</th>
      <th scope="col">Seats</th>
      <th scope="col">Price</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @events.each do |event| %>
      <tr>
        <td><%= event.name %></td>
        <td><%= event.date %></td>
        <td><%= event.location %></td>
        <td><%= event.seats %></td>
        <td><%= event.price %></td>
        <td><%= link_to 'Show', event %></td>
        <% if event.seats != 0 %>
          <td><button type="button" class="btn btn-outline-success"><%= link_to 'Buy', ticketing_code_path(:name => @name, :email => @email, :event => event), data: { confirm: 'Are you sure you want to pay ' + event.price.to_s + '$ ?' } %></button></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Event', new_event_path %>

app/views/events/new.html.erb
<h1>New Event</h1>

<%= render 'form', event: @event %>

<%= link_to 'Back', events_path %>

app/views/events/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @event.name %>
</p>

<p>
  <strong>Date:</strong>
  <%= @event.date %>
</p>

<p>
  <strong>Location:</strong>
  <%= @event.location %>
</p>

<p>
  <strong>Seats:</strong>
  <%= @event.seats %>
</p>

<p>
  <strong>Price:</strong>
  <%= @event.price %>
</p>
<%= link_to 'Back', events_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Ticketing</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/ticketing/code.html.erb
<h1>Hello, <%= @name + ':)'%></h1>
<h2>This is your entry ticket code:</h2>
<h3><%= @code %></h3>

<h2>Have fun !!</h2>

<%= link_to 'You can see all your friends here', tickets_path %>

app/views/ticketing/index.html.erb
<%= form_with url: events_path, local: true, method: :get do %>
  <div style="width:30%; margin:0 auto">
    <h1>It's time to party!</h1>
      <div class="form-group">
        <%= label_tag "name", "Your name:" %>
        <input class="form-control" style="width: 400px" <%= text_field_tag "name", nil, :required => true %>
      </div>

      <div class="form-group">
      <%= label "email", "Your email:" %>
        <input class="form-control" style="width: 400px"  <%= text_field_tag "email", nil, :required => true %>
      </div>

      <%= button_tag(type: 'submit', class: "btn btn-primary") do %>Submit <% end %>
  </div>
<% end %>

app/views/tickets/_form.html.erb
<%= form_with(model: ticket) do |form| %>
  <% if ticket.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(ticket.errors.count, "error") %> prohibited this ticket from being saved:</h2>

      <ul>
        <% ticket.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email %>
  </div>

  <div class="field">
    <%= form.label :event %>
    <%= form.text_field :event %>
  </div>

  <div class="field">
    <%= form.label :code %>
    <%= form.string :code %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/tickets/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Tickets</h1>

<table class ="table">
  <thead>
    <tr>
      <th scope="col">Name</th>
      <th scope="col">Email</th>
      <th scope="col">Event</th>
      <th scope="col">Code</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @tickets.each do |ticket| %>
      <tr>
        <td><%= ticket.name %></td>
        <td><%= ticket.email %></td>
        <td><%= ticket.event %></td>
        <td><%= ticket.code %></td>
        <td><%= link_to 'Show', ticket %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/tickets/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @ticket.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @ticket.email %>
</p>

<p>
  <strong>Event:</strong>
  <%= @ticket.event %>
</p>

<p>
  <strong>Code:</strong>
  <%= @ticket.code %>
</p>

<%= link_to 'Back', tickets_path %>